### ISSUE TITLE
删除黑客松接口无效

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/open-hackathon-api#162]
@juniwang 只修改了更新时间，但并没有删除。

测试页面：https://open-hackathon.vercel.app/admin/

---

顺便问一下，下线黑客松是哪个接口？

**Comment by TechQuery** [comment]
@juniwang 开发过程中建了很多_测试活动_，新用户也可能创建_作废的活动_，还是有**真删除**需求的。

**Comment by TechQuery** [comment]
@juniwang 或者规定 **过期且 0 颁奖的活动可真删**，其它只能下线。

**Comment by juniwang** [comment]
已经修改为offline状态所有人不可见。稍后加上“0颁奖方可删除”

**Comment by juniwang** [comment]
已修改:
- 任何管理员可删除
- 删除之后所有人不可见
- 只读活动不能删除。
- 有颁奖的活动不能删除，删除所有颁奖之后可以删除活动。
