### ISSUE TITLE
建议增加团队搜索接口

### ISSUE THREAD

**Issue by Soecka** [kaiyuanshe/open-hackathon-api#243]
-  需求表述： 活动管理团队奖项设置页需要实现一个团队搜索的功能，目前的后端接口只能搜索团队ID，建议增加团队名称关键词作为搜索字段
- https://github.com/kaiyuanshe/OpenHackathon-Web/issues/26

![image](https://user-images.githubusercontent.com/32708404/174701272-3cc8b7c8-2860-40f6-8b5a-bd5f7b42bc7c.png)

**Comment by juniwang** [comment]
@Soecka  是需要新增搜索接口？能否用目前的team list接口，前端过滤？

**Comment by juniwang** [comment]
team list api updated: can search by name: `/v2/hackathon/{hackathonName}/teams?search={keyword}`.

![image](https://user-images.githubusercontent.com/8814383/182866060-ba18cfac-cb98-4a86-88c6-db431d6d27eb.png)
