### ISSUE TITLE
建议增加活动主办方信息接口

### ISSUE THREAD

**Issue by Soecka** [kaiyuanshe/open-hackathon-api#244]
- 需求表述： 活动管理页面下，每个活动有不同的主办方，需要展示活动主办方信息
- 主办方信息格式： 主办方名称，主办方描述文字，主办方LOGO
- 功能：需要能够上传主办方LOGO，编辑和修改主办方名称及描述文字

**Comment by juniwang** [comment]
Working in progress

**Comment by juniwang** [comment]
Added

![image](https://user-images.githubusercontent.com/8814383/178005585-a4aef3d7-ee34-4632-acc6-e87f66fc0fcb.png)
