### ISSUE TITLE
建议增加公告接口

### ISSUE THREAD

**Issue by Soecka** [kaiyuanshe/open-hackathon-api#245]
- 需求表述：活动管理下公告页面，展示活动公告
- 公告格式：标题+内容

**Comment by juniwang** [comment]
公告是平台公告还是不同的活动有不同的公告？

**Comment by Soecka** [comment]
> 公告是平台公告还是不同的活动有不同的公告？

不同活动有不同公告

**Comment by juniwang** [comment]
Completed: https://hackathon-api.kaiyuanshe.cn/swagger/index.html
![image](https://user-images.githubusercontent.com/8814383/180775989-c62cbcd6-b3eb-4cc1-b66c-c2f1426fd94c.png)
