### ISSUE TITLE
活动报名问卷自定义接口

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/open-hackathon-api#337]
## 数据结构

https://github.com/kaiyuanshe/OpenHackathon-Web/blob/551ed343e414d055864ed55c56a3a985576aa04d/models/Question.ts#L1-L7

**Comment by hsupu** [comment]
@TechQuery 关于数据结构，为了灵活，我提议后端使用类似于现有表单（Enrollment）的 Extension (name, value) 结构。

这样是否可以？

例如：

```
{
  extensions: [
    {
      name: '您的专业',
      value: JSON.stringify({
        title: string;
        options?: string[];
        multiple?: boolean;
        type?: 'text' | 'url';
        required?: boolean;
      })
    }
  ]
}
```

参见 https://github.com/kaiyuanshe/open-hackathon-api/pull/338/files :: src/open-hackathon-server/Kaiyuanshe.OpenHackathon.Server/Models/Questionnaire.cs
