### ISSUE TITLE
活动主页报名人数和实际报名人数不一致

### ISSUE THREAD

**Issue by Soecka** [kaiyuanshe/open-hackathon-api#368]
![image](https://user-images.githubusercontent.com/32708404/205490961-e34a056e-6809-4b51-9800-ec9045dc652a.png)
20221204 ，实际人数41

**Comment by hsupu** [comment]
目前，公开的报名人数（字段名 enrollment）是经批准的值。

```
/// <summary>
/// Number of enrolled users. Only approved enrollments are counted.
/// </summary>
/// <example>100</example>
public int enrollment { get; set; }
```

目前我在线上版本观察列表页和详情页，也未有不一致现象。这个问题请问有什么方法可以复现吗？
